### ISSUE TITLE
[Bug] Shortcuts which involve 'Alt' key lead to insertion of random character

### ISSUE THREAD

**Issue by pidgeon777** [dail8859/SurroundSelection#10]
Hello, I'm using Notepad++ v7.6.3 32-bit and I made these associations:

- Select and Find Next -> Alt+Down
- Select and Find Previous -> Alt+Up

This is the result when I release the 'Alt' key with the latest v1.3 version of SurroundSelection enabled:

![mRck4QlNYk](https://user-images.githubusercontent.com/13739892/59336173-5361a200-8cfe-11e9-87b0-4da2ab45b82c.gif)

**Comment by dail8859** [comment]
Do you know if this same thing happens with Notepad++ v7.7 32-bit and SurroundSelection v1.3?

I don't have any way to test it currently and I'm wondering if something to do with the major v7.7 update is to blame.

**Comment by pidgeon777** [comment]
I've not verified the bug against the 7.7 version. If needed I could download a portable v7.7 32-bit release to test it, eventually. Please let me know.

Thanks!

**Comment by dail8859** [comment]
If you get a chance that would be great, but if not I can test it out myself when I get some free time.

**Comment by pidgeon777** [comment]
I confirm this issue also exists on v7.7 32-bit, unfortunately.

**Comment by dail8859** [comment]
Thanks for testing it out! I'll see what I can figure out when I get a chance to dig into it more

**Comment by dail8859** [comment]
@pidgeon777 

A new DLL can be downloaded which should fix this issue. If there are no issues found I'll create another release soon.

- 32 bit version: https://ci.appveyor.com/project/dail8859/surroundselection/build/job/mw0pyedreyktb37w/artifacts
- 64 bit version: https://ci.appveyor.com/project/dail8859/surroundselection/build/job/cmcqb691stc6bnl4/artifacts
