### ISSUE TITLE
Version 1.3 zip issue for PluginAdmin

### ISSUE THREAD

**Issue by chcg** [dail8859/SurroundSelection#11]
The dll contains an extra dir SurroundSelection in the zip file, see https://github.com/dail8859/SurroundSelection/releases/download/v1.3/SurroundSelection_v1.3.zip. 

Was this done intentionally? This way it can't be used by PluginAdmin.
Probably this was done for the early stages of PA in 7.6.x.

**Comment by dail8859** [comment]
> Was this done intentionally?

I'm....honestly not sure. My goal is to be compatible with the PluginAdmin. I haven't had much free time lately to dedicate to all my various plugins :)

**Comment by chcg** [comment]
@dail8859 For the PA since (as fas as I remember 7.6.2 or 7.6.3) the main plugin dll needs to be in the top level directory of the zip again to be compatible with the needs of PA. So the format of v1.2 is ok, but current v1.3 zip with the extra SurroundSelection dir not. Could you please correct that.

**Comment by dail8859** [comment]
Yeah you are right. I updated the appveyor file and for some reason got in my head it needed to be in a subdirectory. :)

**Comment by dail8859** [comment]
@chcg Thanks for catching this. New release: https://github.com/dail8859/SurroundSelection/releases/tag/v1.3.1
