### ISSUE TITLE
Let the user decide, which surroundings are necessary

### ISSUE THREAD

**Issue by StefanCaemmerer** [dail8859/SurroundSelection#13]
Hello,
I'm programmin in G-Code (CNC machines) and I find this plugin very useful for bracketing my code - only "<", ">" and "{",  "}" are not necessary for me.
Even worse, whenever I want to replace "=" with "<" I get "<=>".

I would prefer, if I could setup, which types of brackets I want to use.

**Comment by dail8859** [comment]
You can download a new DLL from the release page. https://github.com/dail8859/SurroundSelection/releases/tag/v1.4
