### ISSUE TITLE
Feature request : When selected languageis Batch file, please add % to the surround characters list 

### ISSUE THREAD

**Issue by shodanx2** [dail8859/SurroundSelection#18]
Hi,

Variables are expanded using %variable% in batch

Example

set myvar=hello, world
echo %myvar%

I am getting the hang of autoquote surround, but not having it do it consistently for this character is really interrupting my flow !

By language selected I mean this dialog

![image](https://github.com/dail8859/SurroundSelection/assets/10621885/21e7e340-effa-44e6-ae1d-46e1cb1a77bd)

If that cannot be done automatically depending on the language. I would like to have the option on the about page perhaps of the list of characters ? 

Thanks !

**Comment by dail8859** [comment]
Following the readme you can add custom characters.

In `%APPDATA%\Notepad++\plugins\config\SurroundSelection.ini` you can add the line `AdditionalChars=%`

Once Notepad++ is restarted that should work as expected. No way to limit it to just Batch.

**Comment by shodanx2** [comment]
Thank you, works great

I would suggest adding this setting to 
the plugin menu
![image](https://github.com/dail8859/SurroundSelection/assets/10621885/8f227b47-5345-44f6-a1ad-428bd1e07e81)

thanks !
