### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by znsoooo** [dail8859/SurroundSelection#19]
I double-clicked the mouse, held down Ctrl, etc., and there were no special effects.

I am using npp-8.6.7.

Here is the screen recording video:

https://github.com/dail8859/SurroundSelection/assets/34830785/0c777f45-6012-412a-b108-fd26e009f3a4

**Comment by dail8859** [comment]
You are specifically wanting multi-editing capabilities. These are provided by the application, not the plugin.

![image](https://github.com/dail8859/SurroundSelection/assets/3694843/e19b4908-9fb9-429f-a48e-a64a6d7d7562)


You can still use this plugin without the multi-editing turned on too. It is just that the plugin _can_ use multiple selections if they are enabled.

**Comment by znsoooo** [comment]
@dail8859 

I'm not trying to implement multiple choices, I'm using duplicate text just for testing.

What I want to ask is how to enable your plugin's quick selection of parenthesis pairs in text like this? Double-click? Click? Press a modify key? Press a shortcut? Which character's location is needed to clicked?

**Comment by dail8859** [comment]
> What I want to ask is how to enable your plugin's quick selection of parenthesis pairs in text like this?

This plugin doesn't do that.

Please see the [Usage section](https://github.com/dail8859/SurroundSelection?tab=readme-ov-file#usage) of the readme.

**Comment by znsoooo** [comment]
> Please see the Usage section of the readme.

I don't know why I didn't understand it just now, but now that I understand it, maybe I'm confused.  @_@

**Comment by Korb** [comment]
> Please see the Usage section of the readme.

There is no `Usage` section in `README.md`, only `Installation`, `Development` and `License`. I am here for the same reason as @Znsoooo, because neither the description of the plugin in `Plugins Admin` nor the video in `README.md` explain to me how to use this plugin.

**Comment by dail8859** [comment]
<img width="857" height="615" alt="Image" src="https://github.com/user-attachments/assets/a8385bb7-a317-40e8-90be-4e5f3682ae94" />

**Comment by Korb** [comment]
Please forgive me, my ad blocker decided to play a joke on me:

<img width="506" height="608" alt="Image" src="https://github.com/user-attachments/assets/f89b6e8a-d61d-459a-85a8-0ae9d6ba5b7e" />

🤣
