### ISSUE TITLE
Almost perfect on UK layouts

### ISSUE THREAD

**Issue by AlexBlandin** [dail8859/SurroundSelection#2]
Love the plugin, however UK layouts have a different position for the speech & quote marks, where speech marks are "SHIFT + 2", and while quote appears on the same physical position, logically it maps to the US "#". Is there some way to see what npp parses from the input to give a locale-independent mapping?

**Comment by dail8859** [comment]
Thanks for the info!

The way the plugin works is that it captures the keyboard input before Notepad++ gets a chance to process it. Right now it is very simplistic in how it catches the keyboard input and determines what "character" is typed.

I'm assuming there are some Win32 APIs that could be used to map raw keyboard input, to a specific "character" given the current keyboard layout. Unfortunately I'm not sure how to do that...and don't have alot of free time currently to investigate it more.

It is likely this issue and #1 could be solved by the same solution.

**Comment by dail8859** [comment]
Ok we'll ttatted bug tv ř7hyn

**Comment by AlexBlandin** [comment]
Works perfectly!
