### ISSUE TITLE
Completely deletes text

### ISSUE THREAD

**Issue by CobraHiss** [dail8859/SurroundSelection#4]
Hey,

I'm using version 1.1 and it seems to just delete the text completely rather than surround a selected word.

Do you know what could be causing this?

**Comment by dail8859** [comment]
Two things immediately come to mind...make sure it is enabled through the plugin menu and also it may not work correctly with non-US keyboard layouts.

If it is enabled and you are using a US keyboard then I'd recommend posting your Notepad++ debug info along with the exact steps you are trying.

**Comment by CobraHiss** [comment]
I am using a US keyboard and I have SurroundSelection enabled through the plugin menu.

What I did was this:

- Downloaded 32-bit version of the plugin
- Unzipped it, dragged the DLL into plugins folder of Notepad++
- Opened Notepad++ and enabled it from Plugins menu

I open a new tab, type some words in there and then hold SHIFT and press arrow back button to select a word. After that I do SHIFT + ' to surround the selected word with "". It just deletes everything in the opened tab.

Not exactly sure how debug works on Notepad++.

**Comment by dail8859** [comment]
> Not exactly sure how debug works on Notepad++.

Use the menu `? > Debug Info...` and copy/paste that information here.

**Comment by CobraHiss** [comment]
Hey Dail, sorry, it turns out it was my fault. I was running Notepad++ version 6.6.9. SurroundSelection is not compatible with it. And that's why I was not aware that Debug Info even existed. I've upgraded to the latest version now and everything is working perfectly. Thank you!

**Comment by dail8859** [comment]
Glad it is working for you now.
